### ISSUE TITLE
find_maxima.pyx is missing from find_maxima cython directory

### ISSUE THREAD

**Issue by michalstepniewski** [dwaithe/MaximaFinder#1]
find_maxima.pyx is missing from find_maxima cython directory
Can I find it in the repo somewhere else? (there is info here that this is a new repo)

**Comment by dwaithe** [comment]
Thanks! I am not sure how that happened. It is now there.

**Comment by Aliktk** [comment]
@michalstepniewski brother I am sorry to mention but I facing an issue while installing the pip package can you please guide me on how to use it manually or install the package correctly?
I also raise an issue in #3 but waiting for the response.

Thanks

**Comment by xuandong93** [comment]
Hi!
I have installed using python setup.py install and tried to run find_maxima.ipynb but got this error : 

ModuleNotFoundError: No module named 'findmaxima2d.cfindmaxima2d'
