### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by ZLoverty** [dwaithe/MaximaFinder#5]
Hello, I'm trying to install this package on a Windows 10 PC, with `python3 -m pip install findmaxima2d`. I get the following error message.

![image](https://user-images.githubusercontent.com/20690573/200838195-a0743005-b6bc-4da7-bfbf-f79aa50f875c.png)

I tried to upgrade my pip, and use command `pip install findmaxima2d`, they do not work either. 

Do you have a clue what is happening?

**Comment by gabrieltorresgamez** [comment]
Hey @ZLoverty,

I'm encountering the same error. Since this issue is quite old, I'd be interested to know if you found a quick fix or an alternative.

**Comment by pavelzach** [comment]
Hi all, I was able to install it using Python 3.11, with a pre-installed numpy, scipy and Cython. Together with the MS C++ Build Tools.
