### ISSUE TITLE
Error Importing findmaxima2d in Google Colab

### ISSUE THREAD

**Issue by navyn007** [dwaithe/MaximaFinder#8]
Hiya,

I have been trying to import this package into google colab but i'm being met with this error,

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-23-e61b81e5ff51>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 
----> 4 from findmaxima2d import findmaxima2d

2 frames
[/usr/local/lib/python3.10/dist-packages/findmaxima2d/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .findmaxima2d import find_local_maxima, find_maxima

[/usr/local/lib/python3.10/dist-packages/findmaxima2d/findmaxima2d.py](https://localhost:8080/#) in <module>
      1 import numpy as np
      2 from scipy import ndimage
----> 3 from .cfindmaxima2d import find_maxima as cfind_maxima
      4 
      5 def find_local_maxima(img_data,size=3):

/usr/local/lib/python3.10/dist-packages/findmaxima2d/cfindmaxima2d.pyx in init findmaxima2d.cfindmaxima2d()

ModuleNotFoundError: No module named 'is_within'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

Any tips ?

**Comment by farzin23i** [comment]
Same issue here! Just installed it via pip.

**Comment by mocarl** [comment]
Getting the same error in Windows. Works on MacOS though.

```
from .cfindmaxima2d import find_maxima as cfind_maxima
  File "findmaxima2d\\cfindmaxima2d.pyx", line 7, in init findmaxima2d.cfindmaxima2d
ModuleNotFoundError: No module named 'is_within'
```

**Comment by dwaithe** [comment]
Hi gang, sorry for the delay. I had to update the pip repository as well. It should work now, and I have tested in Google collab. Please use:
pip install findmaxima2d==0.0.27
To be sure you have the correct version installed.

<img width="956" alt="Screenshot 2024-08-26 at 18 24 41" src="https://github.com/user-attachments/assets/c1d72812-553c-4d48-89dc-cbdab8aa4a98">
Thanks for your patience. I just have a billion things to do these dadys.

**Comment by navyn007** [comment]
Thank you so much, @dwaithe. You just saved my internship! I really appreciate your effort man :)
